export const LANGUAGE_CONFIG = {
    en: {
        code: "en",
        label: "English",
        translatorCode: "en",
        geminiName: "English",
        locale: "en-US",
    },
    es: {
        code: "es",
        label: "Spanish",
        translatorCode: "es",
        geminiName: "Spanish",
        locale: "es-ES",
    },
    fr: {
        code: "fr",
        label: "French",
        translatorCode: "fr",
        geminiName: "French",
        locale: "fr-FR",
    },
    de: {
        code: "de",
        label: "German",
        translatorCode: "de",
        geminiName: "German",
        locale: "de-DE",
    },
    it: {
        code: "it",
        label: "Italian",
        translatorCode: "it",
        geminiName: "Italian",
        locale: "it-IT",
    },
    pt: {
        code: "pt",
        label: "Portuguese",
        translatorCode: "pt",
        geminiName: "Portuguese",
        locale: "pt-BR",
    },
    ru: {
        code: "ru",
        label: "Russian",
        translatorCode: "ru",
        geminiName: "Russian",
        locale: "ru-RU",
    },
    ar: {
        code: "ar",
        label: "Arabic",
        translatorCode: "ar",
        geminiName: "Arabic",
        locale: "ar-SA",
    },
    zh: {
        code: "zh",
        label: "Chinese",
        translatorCode: "zh-CN",
        geminiName: "Chinese",
        locale: "zh-CN",
    },
    ja: {
        code: "ja",
        label: "Japanese",
        translatorCode: "ja",
        geminiName: "Japanese",
        locale: "ja-JP",
    },
    ko: {
        code: "ko",
        label: "Korean",
        translatorCode: "ko",
        geminiName: "Korean",
        locale: "ko-KR",
    },
    hi: {
        code: "hi",
        label: "Hindi",
        translatorCode: "hi",
        geminiName: "Hindi",
        locale: "hi-IN",
    },
    vi: {
        code: "vi",
        label: "Vietnamese",
        translatorCode: "vi",
        geminiName: "Vietnamese",
        locale: "vi-VN",
    },
    id: {
        code: "id",
        label: "Indonesian",
        translatorCode: "id",
        geminiName: "Indonesian",
        locale: "id-ID",
    },
    tr: {
        code: "tr",
        label: "Turkish",
        translatorCode: "tr",
        geminiName: "Turkish",
        locale: "tr-TR",
    },
    sw: {
        code: "sw",
        label: "Swahili",
        translatorCode: "sw",
        geminiName: "Swahili",
        locale: "sw-KE",
    },
};

export const DEFAULT_LANGUAGE = "en";

